config/routes.rb
Rails.application.routes.draw do
  root to: 'developers#index'
  resources :developers, except: :show do
    collection do
      post :create_dummy_data
      get :filter_data
      delete :destroy_all
    end
  end
  resources :languages, except: :show
  resources :programming_languages, except: :show
  namespace :api do
    namespace :v1 do
      resources :developers, only: :show
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :developer_programming_languages
  has_many :developer_languages
  has_many :programming_languages, through: :developer_programming_languages
  has_many :languages, through: :developer_languages

  validates :email, presence: true, uniqueness: true
end

app/models/developer_language.rb
class DeveloperLanguage < ApplicationRecord
  belongs_to :developer
  belongs_to :language
end

app/models/developer_programming_language.rb
class DeveloperProgrammingLanguage < ApplicationRecord
  belongs_to :developer
  belongs_to :programming_language
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :developer_languages
  has_many :developers, through: :developer_languages
  validates :code, presence: true, uniqueness: true
end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
  has_many :developer_programming_languages
  has_many :developers, through: :developer_programming_languages
  validates :name, presence: true, uniqueness: true
end

app/controllers/api/v1/api_controller.rb
module Api::V1
  class ApiController < ActionController::API
    include Response
    include ExceptionHandler
  end
end

app/controllers/api/v1/developers_controller.rb
module Api::V1
  class DevelopersController < ApiController
    def show
      developer = Developer.find(params[:id])
      render json: developer
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/crud.rb
module CRUD
  extend ActiveSupport::Concern

  included do
    before_action :set_entity, only: %i[edit update destroy]
  end

  def index
    @entities = entity_class.all.page params[:page]
  end

  def new
    @entity = entity_class.new
  end

  def edit; end

  def create
    @entity = entity_class.new(entity_params)
    if @entity.save
      redirect_to entity_class
    else
      render :new
    end
  end

  def update
    if @entity.update_attributes(entity_params)
      redirect_to entity_class
    else
      render :edit
    end
  end

  def destroy
    @entity.destroy
    redirect_back(fallback_location: request.referrer)
  end

  protected

  def entity_class
    @entity_class ||= controller_name.classify.constantize
  end

  def entity_params
    params.require(table_name.singularize.to_sym).permit!
  end

  def table_name
    entity_class.table_name
  end

  def set_entity
    @entity = entity_class.find(params[:id])
  end
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController

  def index
    @entities = Developer.joins(:languages, :programming_languages).page params[:page]
  end

  def create_dummy_data
    `bundle exec rake developers:generate_dummy`
    redirect_to developers_path
  end

  def filter_data
    @entities = SearchDevelopersService.new(params_search).perform
    @entities = @entities.page params[:page]
    render :index
  end

  def destroy_all
    Developer.destroy_all
    redirect_to developers_path
  end

  private

  def params_search
    params.require(:filter).permit!
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  include CRUD
end

app/controllers/programming_languages_controller.rb
class ProgrammingLanguagesController < ApplicationController
  include CRUD
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(ctr_name)
    [ctr_name].index(params[:controller]).present? ? 'is-tab-selected' : ''
  end
end

app/views/developers/index.html.haml
.container
  %h2.header Developers
  = link_to "Delete all", destroy_all_developers_path, method: 'DELETE'
  %br
  %br
  = link_to "Create 100 dummy developers", create_dummy_data_developers_path, method: 'post'
  .filter-group
    = form_for 'filter', url: filter_data_developers_path, method: 'get', html: {class: 'form-filter'}  do |f|
      %div
        %span Email:
        = f.text_field 'developer_email'
      %div
        = f.select 'programming_language', options_for_select(ProgrammingLanguage.pluck(:name, :id)), include_blank: 'Select programming language'
      %div
        = f.select 'language', options_for_select(Language.pluck(:code, :id)), include_blank: 'Select language'
      %div
        = f.submit 'Filter'
  - if @entities.any?
    %table
      %tr
        %th Email
        %th Programming languages
        %th Languages
      - @entities.includes(:languages, :programming_languages).each do |developer|
        %tr
          %td
            = developer.email
          %td
            = developer.programming_languages.pluck(:name).join(', ')
          %td
            = developer.languages.pluck(:code).join(', ')
    = paginate @entities
  - else
    %p No data

app/views/languages/_form.html.haml
= simple_form_for language do |f|
  = f.input :code
  = f.button :submit

app/views/languages/edit.html.haml
= render partial: 'form', locals: {language: @entity}

app/views/languages/index.html.haml
.container
  %h2.header Languages
  = link_to "Add new", new_language_path
  - if @entities.any?
    %table
      %tr
        %th Code
        %th actions
      - @entities.each do |language|
        %tr
          %td
            = language.code
          %td
            = link_to "Edit", edit_language_path(language)
            = link_to "Delete", language_path(language), method: 'DELETE'
  - else
    %p No data

app/views/languages/new.html.haml
= render partial: 'form', locals: {language: @entity}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CodeingExam
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav
      .tabs
        %a.tab{href: root_path, class: active_class('developers')} Developers
        %a.tab{href: languages_path, class: active_class('languages')} Languages
        %a.tab{href: programming_languages_path, class: active_class('programming_languages')} Programming languages
    %main
    = yield

app/views/programming_languages/_form.html.haml
= simple_form_for programming_language do |f|
  = f.input :name
  = f.button :submit

app/views/programming_languages/edit.html.haml
= render partial: 'form', locals: {programming_language: @entity}

app/views/programming_languages/index.html.haml
.container
  %h2.header#aaa Programming Languages
  = link_to "Add new", new_programming_language_path
  - if @entities.any?
    %table
      %tr
        %th Name
        %th actions
      - @entities.each do |programming_language|
        %tr
          %td
            = programming_language.name
          %td
            = link_to "Edit", edit_programming_language_path(programming_language)
            = link_to "Delete", programming_language_path(programming_language), method: 'DELETE'
  - else
    %p No data

app/views/programming_languages/new.html.haml
= render partial: 'form', locals: {programming_language: @entity}